//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Customer_Application
{


    public partial class AdminDashboard
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Table TableBody;

        protected global::System.Web.UI.HtmlControls.HtmlAnchor customersTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor subscriptionsTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor ticketsTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor storesTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor plansTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor accountUsageTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor benefitsTab;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor offersTab;


        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TabHeading;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateContainer1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateLabel1;
        protected global::System.Web.UI.WebControls.TextBox DateInput1;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateContainer2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateLabel2;
        protected global::System.Web.UI.WebControls.TextBox DateInput2;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TextBoxContainer1;
        protected global::System.Web.UI.WebControls.TextBox PlanIDEditText;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TextBoxContainer2;
        protected global::System.Web.UI.WebControls.TextBox MobileEditText;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TextBoxContainer3;
        protected global::System.Web.UI.WebControls.TextBox WalletEditText;

        protected global::System.Web.UI.WebControls.Label LabelOut;

        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.WebControls.Button DeleteButton;
    }
}