//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Customer_Application
{
    public partial class CustomerDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sharedContent;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TabHeading;

        // Start Date Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateContainer1;
        protected global::System.Web.UI.WebControls.Label DateLabel1;
        protected global::System.Web.UI.WebControls.TextBox DateInput1;

        // End Date Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DateContainer2;
        protected global::System.Web.UI.WebControls.Label DateLabel2;
        protected global::System.Web.UI.WebControls.TextBox DateInput2;

        // Plan Name Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PlanNameContainer;
        protected global::System.Web.UI.WebControls.TextBox PlanNameInput;

        // Plan ID Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PlanIDContainer;
        protected global::System.Web.UI.WebControls.TextBox PlanIDInput;

        // Payment Amount Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PaymentAmountContainer;
        protected global::System.Web.UI.WebControls.TextBox PaymentAmountInput;

        // Payment ID Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl PaymentIDContainer;
        protected global::System.Web.UI.WebControls.TextBox PaymentIDInput;


        // Payment Method Dropdown
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DropdownContainer;
        protected global::System.Web.UI.WebControls.DropDownList PaymentMethodDropDown;

        // Benefit ID Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl BenefitIDContainer;
        protected global::System.Web.UI.WebControls.TextBox BenefitIDInput;

        // Voucher ID Input
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl VoucherIDContainer;
        protected global::System.Web.UI.WebControls.TextBox VoucherIDInput;

        // Search Button
        protected global::System.Web.UI.WebControls.Button SearchButton;

        // Label Output
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.Label Label2;

        // Table Body for Results
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TableBody;
    }
}
