//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Customer_Application.AdminDashboard
{


    public partial class CashbackPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label cashbackCount;
        protected global::System.Web.UI.WebControls.Label paymentCount;
        protected global::System.Web.UI.WebControls.PlaceHolder TableBody1;
        protected global::System.Web.UI.WebControls.PlaceHolder TableBody2;
    }
}
