//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Customer_Application.AdminDashboard
{
    public partial class ExclusiveOffersPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TableBody1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TableBody2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl totalOffersCount;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl activeOffersCount;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl expiredOffersCount;
    }
}