//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom_Customer_Application.AdminDashboard
{
    public partial class TransactionsPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TabHeading;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl FilterContainer;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl filterOption1;
        protected global::System.Web.UI.WebControls.TextBox WalletEditText;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl filterOption2;
        protected global::System.Web.UI.WebControls.TextBox DateInput1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl filterOption3;
        protected global::System.Web.UI.WebControls.TextBox DateInput2;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl filterOption4;
        protected global::System.Web.UI.WebControls.Button ApplyFilterButton;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl OutputBanner;
        protected global::System.Web.UI.WebControls.Label AverageSentLabel;
        protected global::System.Web.UI.WebControls.Label AverageReceivedLabel;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TableBody;
    }
}